import { Link } from 'react-router-dom';

function Landing() {
    return (
        <div>
            <h1>The NOBRAC Initiative</h1>
            <p>
                NOBRAC -- carbon spelled in reverse -- is a non-profit campaign geared towards reducing carbon waste in order to help curve the environmental phenomenon known as <strong>global warming</strong>, particularly by raising awareness and serving people with the necessary tools and resources to start making meaningful and impactful changes to their everyday lives.
            </p>
            <Link to="/mission">Click here to learn more</Link>
            <p>
                Global warming is a serious matter and a global crisis that is too critical and vital to our existence and sustainability that it can no longer be ignored. Not only does it influence all domains of life and threatens the security of our food and water, but it also leads to increased flooding, extreme heat, more diseases, and economic loss.
            </p>
            <p>
                In order to take action, it's important to know where we stand. One way to do this is by calculating our carbon footprint. A carbon footprint is the total amount of greenhouse gases (carbon dioxide and other air pollutants) that are generated by our actions. One common way to measure our carbon emissions is by collecting a series of data that translates to a figure denoted as CO₂e, or carbon dioxide equivalent.
            </p>
            <p>
                The average carbon footprint for a person in the United States is between 16 and 20 tonnes (depending on the source), which is the highest in the world after China, although recent data suggests a slight improvement from these numbers: around 14 tonnes. However, compared to the global average of about 4 tonnes, this improvement is still a drop in the bucket.  It is said that in order to avoid a 2°C rise in global temperatures, we must aim to reach under 2 tonnes by 2050. Want to find out what your carbon footprint is?
            </p>
            <p>Take a quick survey to calculate your carbon footprint!</p>
            <Link to="/survey/vehicle">Start</Link>
            <br /><br />
            <div>
                Sources:
                <ol>
                    <li>
                        https://www.nature.org/en-us/get-involved/how-to-help/carbon-footprint-calculator/
                    </li>
                </ol>
            </div>
        </div>
    );
}

export default Landing;